### ISSUE TITLE
我已经进入web..whatsapp.com了但是报错了

### ISSUE THREAD

**Issue by zhengshengjie666** [Auties00/WhatsappWebRequestAnalyzer#12]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class it.auties.analyzer.CryptoKt
        at it.auties.analyzer.MainKt.main$lambda-3(main.kt:19)
        at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.openqa.selenium.devtools.Connection.handle(Connection.java:257)
        at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58)
        at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199)
        ... 3 more

**Comment by Auties00** [comment]
> Caused by: java.lang.NoClassDefFoundError: Could not initialize class it.auties.analyzer.CryptoKt at it.auties.analyzer.MainKt.main$lambda-3(main.kt:19) at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:288) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) at org.openqa.selenium.devtools.Connection.handle(Connection.java:257) at org.openqa.selenium.devtools.Connection.access$200(Connection.java:58) at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:199) ... 3 more

Did you compile the project yourself?

**Comment by zhengshengjie666** [comment]
idea 需要设置为jdk17-preview并且gradle配置中kotlin和idea中的版本号保持一致
