### ISSUE TITLE
lateinit property whatsappKeys has not been initialized

### ISSUE THREAD

**Issue by FreedomLabsIO** [Auties00/WhatsappWebRequestAnalyzer#14]
Hi @Auties00  
Seems the latest release of this [WhatsappWebRequestAnalyzer] is not working anymore. Can you upload a new working release?

Thanks!

```
Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: lateinit property whatsappKeys has not been initialized
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'DESKTOP-ABBT001', ip: '192.168.1.67', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.2'
Driver info: DevTools Connection
        at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:190)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property whatsappKeys has not been initialized
        at it.auties.analyzer.MainKt.getWhatsappKeys(main.kt:44)
        at it.auties.analyzer.MainKt.onBreakpointTriggered(main.kt:249)
        at it.auties.analyzer.MainKt.main$lambda-2(main.kt:60)
        at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:274)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.openqa.selenium.devtools.Connection.handle(Connection.java:243)
        at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
        at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
        ... 3 more
```

**Comment by FreedomLabsIO** [comment]
@Auties00 ?

**Comment by Auties00** [comment]
> @Auties00 ?

Try with the latest commit

**Comment by FreedomLabsIO** [comment]
> > @Auties00 ?
> 
> Try with the latest commit

Can't compile

As there's no RC27 in the Maven repository (https://search.maven.org/artifact/com.github.auties00/whatsappweb4j)
I changed build.gradle.kts dependencies to:
`implementation("com.github.auties00", "whatsappweb4j", "3.0-RC26")`

Then I get this error

```
> Task :compileKotlin FAILED
e: E:\whatsappinvestigation\WhatsappWebRequestAnalyzer\src\main\kotlin\it\auties\analyzer\crypto.kt: (39, 40): Unresolved reference: cipher

FAILURE: Build failed with an exception.
```

**Comment by Auties00** [comment]
> > > @Auties00 ?
> > 
> > 
> > Try with the latest commit
> 
> Can't compile
> 
> As there's no RC27 in the Maven repository (https://search.maven.org/artifact/com.github.auties00/whatsappweb4j) I changed build.gradle.kts dependencies to: `implementation("com.github.auties00", "whatsappweb4j", "3.0-RC26")`
> 
> Then I get this error
> 
> ```
> > Task :compileKotlin FAILED
> e: E:\whatsappinvestigation\WhatsappWebRequestAnalyzer\src\main\kotlin\it\auties\analyzer\crypto.kt: (39, 40): Unresolved reference: cipher
> 
> FAILURE: Build failed with an exception.
> ```

Build the latest commit of whatsappweb4j and use it as a dependency for this project, should work

**Comment by FreedomLabsIO** [comment]
> > > > @Auties00 ?
> > > 
> > > 
> > > Try with the latest commit
> > 
> > 
> > Can't compile
> > As there's no RC27 in the Maven repository (https://search.maven.org/artifact/com.github.auties00/whatsappweb4j) I changed build.gradle.kts dependencies to: `implementation("com.github.auties00", "whatsappweb4j", "3.0-RC26")`
> > Then I get this error
> > ```
> > > Task :compileKotlin FAILED
> > e: E:\whatsappinvestigation\WhatsappWebRequestAnalyzer\src\main\kotlin\it\auties\analyzer\crypto.kt: (39, 40): Unresolved reference: cipher
> > 
> > FAILURE: Build failed with an exception.
> > ```
> 
> Build the latest commit of whatsappweb4j and use it as a dependency for this project, should work

It worked. Thanks!
