### ISSUE TITLE
Error: lateinit property whatsappKeys has not been initialized

### ISSUE THREAD

**Issue by mafeth** [Auties00/WhatsappWebRequestAnalyzer#4]
Getting this error when scanning the QR Code with my phone and everytime a new json message is received.

Java: 16.0.1
Chrome: 90.0.4430.72

`Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: lateinit property whatsappKeys has not been initialized
Build info: version: '4.0.0-beta-3', revision: '5d108f9a67'
System info: host: 'PCName', ip: 'IP', os.name: 'Operating Systm', os.arch: 'Architecture', os.version: 'OSVersion', java.version: '16.0.1'
Driver info: DevTools Connection
        at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:190)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property whatsappKeys has not been initialized
        at it.auties.whatsapp4j.MainKt.decodeBase64EncodedBinaryMessage(main.kt:113)
        at it.auties.whatsapp4j.MainKt.decodeBase64EncodedBinaryMessage$default(main.kt:107)
        at it.auties.whatsapp4j.MainKt.onMessageReceived(main.kt:74)
        at it.auties.whatsapp4j.MainKt$main$4.accept(main.kt:43)
        at it.auties.whatsapp4j.MainKt$main$4.accept(main.kt)
        at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:274)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at org.openqa.selenium.devtools.Connection.handle(Connection.java:243)
        at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55)
        at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187)
        ... 3 more`

**Comment by Auties00** [comment]
> Getting this error when scanning the QR Code with my phone and everytime a new json message is received.
> 
> Java: 16.0.1
> Chrome: 90.0.4430.72
> 
> `Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: lateinit property whatsappKeys has not been initialized Build info: version: '4.0.0-beta-3', revision: '5d108f9a67' System info: host: 'PCName', ip: 'IP', os.name: 'Operating Systm', os.arch: 'Architecture', os.version: 'OSVersion', java.version: '16.0.1' Driver info: DevTools Connection at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:190) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:831) Caused by: kotlin.UninitializedPropertyAccessException: lateinit property whatsappKeys has not been initialized at it.auties.whatsapp4j.MainKt.decodeBase64EncodedBinaryMessage(main.kt:113) at it.auties.whatsapp4j.MainKt.decodeBase64EncodedBinaryMessage$default(main.kt:107) at it.auties.whatsapp4j.MainKt.onMessageReceived(main.kt:74) at it.auties.whatsapp4j.MainKt$main$4.accept(main.kt:43) at it.auties.whatsapp4j.MainKt$main$4.accept(main.kt) at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:274) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) at org.openqa.selenium.devtools.Connection.handle(Connection.java:243) at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55) at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187) ... 3 more`

whatsapp has probably changed the key property, i'll fix this issue asap

**Comment by Auties00** [comment]
> Getting this error when scanning the QR Code with my phone and everytime a new json message is received.
> 
> Java: 16.0.1
> Chrome: 90.0.4430.72
> 
> `Exception in thread "CDP Connection" org.openqa.selenium.devtools.DevToolsException: lateinit property whatsappKeys has not been initialized Build info: version: '4.0.0-beta-3', revision: '5d108f9a67' System info: host: 'PCName', ip: 'IP', os.name: 'Operating Systm', os.arch: 'Architecture', os.version: 'OSVersion', java.version: '16.0.1' Driver info: DevTools Connection at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:190) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) at java.base/java.lang.Thread.run(Thread.java:831) Caused by: kotlin.UninitializedPropertyAccessException: lateinit property whatsappKeys has not been initialized at it.auties.whatsapp4j.MainKt.decodeBase64EncodedBinaryMessage(main.kt:113) at it.auties.whatsapp4j.MainKt.decodeBase64EncodedBinaryMessage$default(main.kt:107) at it.auties.whatsapp4j.MainKt.onMessageReceived(main.kt:74) at it.auties.whatsapp4j.MainKt$main$4.accept(main.kt:43) at it.auties.whatsapp4j.MainKt$main$4.accept(main.kt) at org.openqa.selenium.devtools.Connection.lambda$handle$6(Connection.java:274) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541) at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) at org.openqa.selenium.devtools.Connection.handle(Connection.java:243) at org.openqa.selenium.devtools.Connection.access$200(Connection.java:55) at org.openqa.selenium.devtools.Connection$Listener.lambda$onText$0(Connection.java:187) ... 3 more`

Fixed in the latest commit!
